### ISSUE TITLE
Feature request: recursive icon_path

### ISSUE THREAD

**Issue by imsamuka** [dunst-project/dunst#1002]
It really is a shame that the `icon_path` option isn't able to look up at sub-directories.
For example, mine looks like this:

```ini
icon_path = /usr/share/icons/Papirus-Dark/48x48/actions/:/usr/share/icons/Papirus-Dark/48x48/apps/:/usr/share/icons/Papirus-Dark/48x48/devices/:/usr/share/icons/Papirus-Dark/48x48/emblems/:/usr/share/icons/Papirus-Dark/48x48/emotes/:/usr/share/icons/Papirus-Dark/48x48/mimetypes/:/usr/share/icons/Papirus-Dark/48x48/places/:/usr/share/icons/Papirus-Dark/48x48/status/:/usr/share/icons/Papirus-Dark/symbolic/actions/
```

If it could look at sub-directories, it could be replaced with:

```ini
icon_path = /usr/share/icons/Papirus-Dark/48x48/:/usr/share/icons/Papirus-Dark/symbolic/
```

It is also retro-compatible, so no dunstrc would break with the change. If necessary, it could be activated with another option (`icon_path_recursive = yes`) as well.

**Comment by fwsmit** [comment]
You're in luck, something similar is already implemented. Instead of the `icon_path`, you can set:

```ini
[global]
    enable_recursive_icon_lookup = true # enable recursive icon lookup
    icon_theme = Papirus-Dark
    icon_size = 48
```

It is standards-compatible and will search the theme and inherited themes for icons that can scale to a size of 48.

It will be enabled by default in the next major release of dunst. Suggestions about improvements are very welcome.

**Comment by imsamuka** [comment]
Ohooo, i will right now. Some questions that lead to some improvements:
* It also get the symbolic icons? (i.e `/usr/share/icons/Papirus-Dark/symbolic/`)
* If it don't find a 48x48 icon, it fallback to the next smaller size?
  * If the fallback reach `min_icon_size`, what happens?
* Will `max_icon_size` be deprecated?

**Comment by fwsmit** [comment]
Thanks for the feedback, here's some answers and more:

> Ohooo, i will test right now. Some questions that lead to some improvements:
> 
>     * ~It also get the symbolic icons? (i.e /usr/share/icons/Papirus-Dark/symbolic/)~ Yes!

Indeed.

> 
>     * If it don't find a 48x48 icon, it fallback to the next smaller size?

No

>       
>       * If the fallback reach `min_icon_size`, what happens?
> 
>     * Will `max_icon_size` be deprecated?

Min and max size are currently ignored for icons from your icon theme. I believe they are still used for icons that are not part of your icon theme.
I haven't entirely thought through if and how to combine the configuration of icons from you icon theme with icons that are passed via path or raw via dbus. These icons may or may not be scalable and are just one size. Ideally you'd want to configure these separately, but I don't want to make the icon configuration too complicated.
Maybe it'll just be enough for `icon_size` to be a rule (it is now), so that people can configure the icon size per application. See https://github.com/dunst-project/dunst/issues/992 for the issue I made about this.

> 
>     * Or is the other way around?

I'm not sure what you mean by this one.

If you want more information on how the recursive icon implementation works, it follows the [spec](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html) pretty closely.

**Comment by imsamuka** [comment]
> `* Or is the other way around?`
> I'm not sure what you mean by this one.

I assumed the icon size would fallback until `min_icon_size`, but it could be to `max_icon_size` instead. Sorry for the badly phrasing

> Maybe it'll just be enough for icon_size to be a rule (it is now), so that people can configure the icon size per application. See #992 for the issue I made about this.

I think this is the best solution, ideally one would probably want consistent icon sizes for all notifications, or one custom size per specific application/match.

Closing this, continuing in #992.
