### ISSUE TITLE
Focus window on click notification?

### ISSUE THREAD

**Issue by victorbnl** [dunst-project/dunst#1045]
I'd like to have a functionnality to focus the window that sent the notification when it's clicked.

Some apps already do that but it's pretty random; Discord marks the window as urgent, Instagram does nothing, some notification tester makes the Firefox window focus (expected behaviour)...

I'd see that as an option in the mouse actions such as

```ini
[global]
    mouse_left_click = focus
```

The goal would be to have that controlled by dunst so that this behaviour does not depend only on the applications anymore.

**Comment by fwsmit** [comment]
I'm afraid this would be very hard to implement. Do you know of a way this could be implemented?
The only thing I can think of is using some information from the [desktop file](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html), like the `StartupWMClass`, to find the window.

**Comment by victorbnl** [comment]
Honestly I don't really know, I'll think about it but it can indeed be difficult

**Comment by bebehei** [comment]
This is not possible to implement.

The data, which is going over the wire does not contain any information about the actual window. There might not be a window (see `notify-send`) or the window is closed, since the app lives in the tray while sending the notification.

Sadly, as you have mentioned it, this must be done in every application.

**Comment by victorbnl** [comment]
Oh right, indeed

**Comment by i007c** [comment]
@victorbnl i think you can implemented locally
for example i use `dwm` and my discord window is alway on tag 9
i believe that it's possible to make a connection between `dunst` and `dwm` so that whenever 
a notif came from discord change the dwm tag to 9

but this is not a general solution
and its depends on your setup and your use cases.

**Comment by mark2185** [comment]
This does seem to work for `chromium` based browsers, but not for `firefox`, for some reason.

I can invoke `dunst action` and `i3` will mark the workspace as `urgent` and the window will be brought up to the top. That's how I open my `slack` notifications, and it works great.

But now I switched to `firefox` and I'm missing said feature. Couldn't find any related issue, does anyone have more info?
