### ISSUE TITLE
Feature request: Keyboard shortcut for `do_action, close_current`

### ISSUE THREAD

**Issue by thobias-karlsson-wcar** [dunst-project/dunst#1048]
### Issue description
Dunst is awesome. I'm using `close = ctrl+space` to close/ignore notification, but when you want to act on a notification it would be nice to `mod` this command and get to the notification source, e.g `ctrl+mod4+space`. We can assign this to mouse, e.g. `mouse_middle_click = do_action, close_current`, but using the mouse for this is cumbersome. Is there, or could there be, any way of defining a keyboard shortcut to those two actions?

### Installation info

- Version: `Dunst - A customizable and lightweight notification-daemon 1.4.1 (2019-07-03)`
- Install type: `package`
- Window manager / Desktop environment: `Ubuntu`

<details>
<summary>Minimal dunstrc</summary>

```ini
# N/A
```
</details>

**Comment by fwsmit** [comment]
You can use `dunstctl action [POSITION]` for activating an action. I don't know if it will close the notification afterwards though.

It's currently not possible from the dunstrc configuration, since the original plan was to remove the keyboard shortcuts from dunstrc entirely to replace them with dunstctl. The shortcuts will stay in the dunstrc now, though.

**Comment by fwsmit** [comment]
@thobias-karlsson-wcar is `dunstctl action` good enough for you?

**Comment by thobias-karlsson-wcar** [comment]
Thank you @fwsmit ! Sorry I didn't catch your reply. That's absolutely enough! :)
