### ISSUE TITLE
Ubuntu repository hasn't been updated since version 1.5.0 (2020-07-23)

### ISSUE THREAD

**Issue by a-pav** [dunst-project/dunst#1111]
Most `dunstrc`configurations I've found do not work. Did a lot of digging and at last, I realized that apparently dunst has changed a lot since `1.5.0 (2020-07-23)`.

**Comment by bebehei** [comment]
Hi @a-pav 

this is a typical "problem" of Ubuntu and Debian release model. Once Debian or Ubuntu does a release, it freezes all included package versions for this release. If new versions of the upstream software are released, the ubuntu/Debian still package won't get the update.

Only exception is a security upgrade or bugfix, which is tracked in the Debian Bugtracker. But then, only the fix will get backported and not the rest of the features.

All in All, you'll get with Debian/Ubuntu a very stable system by this.

This is totally a problem of the distro and not related to dunst. Nobody of the dunst maintainer can bend the rule of the distro.

You can see on repology, which Debian/Ubuntu releases include which dunst version: https://repology.org/project/dunst/versions

You can find the release policy of Debian here: https://wiki.debian.org/DebianReleases. Since Ubuntu has similar release policies, most if it is true for Ubuntu, too.

Since nobody of dunst can have influence on this, I'm going to close it.

---

@tsipinakis repology.org still lists 1.8.1 as the version in Debian unstable. Could you update the unstable package there, too?
