### ISSUE TITLE
dunstify vs notify-send differences (mainly speed)

### ISSUE THREAD

**Issue by fritzrehde** [dunst-project/dunst#1118]
### Issue description

I know dunstify includes some more features that notify-send does not support. But when using features both support, are there advantages to using dunstify over notify-send? More specifically, does one execute common features faster/more efficiently?

### Installation info

- Version: `<!-- output of dunst -v -->`
- Install type: `<!-- [package|manually|...] -->`
- Window manager / Desktop environment: `<!--  -->`

<details>
<summary>Minimal dunstrc</summary>

```ini
# Dunstrc here
```
</details>

**Comment by bebehei** [comment]
Hey Fritz, both tools just send data to the DBus API. I don't see any relevant speed or efficiency differences. If there would be any of them, these would be negligible.

However the actual notification manager (dunst, mako, or the default gnome notification manager or other) does have an impact in speed, since these processes do need to decode, store, process, render and the data and maybe schedule some further action.
