### ISSUE TITLE
the configuration file doen't created after installation

### ISSUE THREAD

**Issue by D3ENNY** [dunst-project/dunst#1206]
### Issue description
when i install dunst from arch linux repository (sudo pacman -Syu dunst) it doen't create the configuration example in /etc/xdg/dunst/dunstrc

### Installation info

- Version: `<!-- 1.9.2 -->`
- Install type: `<!-- from repo with pacman -->`
- Window manager / Desktop environment: `<!-- hrprland -->`
- Distro: `<!-- arch linux -->`

<details>
<summary>when i install dunst from arch linux repository (sudo pacman -Syu dunst) it doen't create the configuration example in /etc/xdg/dunst/dunstrc</summary>
</details>

**Comment by Narrat** [comment]
If the file would be missing it would be an Arch issue :) (because packaging)
But not necessary to create a bug, because the file is there. Just a slightly different path.

https://archlinux.org/packages/extra/x86_64/dunst/
```
etc/
etc/dunst/
etc/dunst/dunstrc
```
What is also helpful if you're missing files or want to know file locations: `-Ql` (query and list) -> `pacman -Ql dunst`
