### ISSUE TITLE
[Feature request] Wayland transparency

### ISSUE THREAD

**Issue by oredaze** [dunst-project/dunst#1252]
As the title says, transparency is missing under wayland.

I tried mako, but they have a 5 year old issue still open for dynamic width, so I would like to stay with dunst :)

**Comment by bynect** [comment]
Are you talking about `transparency` option? I know that at the moment is only for X11, but it is "discouraged" since it will set opacity to the whole window anyway and relies on the wm behaving well. A better solution is specifying an alpha component in the colors "#RRGGBBAA". Have you tried doing it with wayland?

**Comment by oredaze** [comment]
Oh, I wasn't aware that there is a second way of setting transparency. That works. Thank you very much.

**Comment by bynect** [comment]
> Oh, I wasn't aware that there is a second way of setting transparency. That works. Thank you very much.

With that way you can specify the transparency of individual colors.
Maybe it should be documented a bit more
