### ISSUE TITLE
dunst crashes with "X Error of failed request:  BadWindow" when closing topmost window

### ISSUE THREAD

**Issue by Gjum** [dunst-project/dunst#141]
When using `follow_mode=keyboard` and dunst is showing a notification and the topmost window is closed, dunst crashes with this error:

```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  40 (X_TranslateCoords)
  Resource id in failed request:  0x2400f2f
  Serial number of failed request:  26729
  Current serial number in output stream:  26729
```

Did anyone else get this before and knows how to fix it?
I am using crunchbang linux with openbox and tint2.
dunst is the newest version (2638178).

**Comment by Eizen** [comment]
This is no longer an issue since almost all window managers have the net property set by now.

**Comment by tsipinakis** [comment]
JFTR This also happens on window managers that do set the active window property if you open and close windows fast enough. This is to be expected when messing with another programs window since from the moment we get a reference of the active window it becomes a race condition if we will process it in time or it will have been closed by the time we make the `XTranslateCoordinates` call.

I don't think there is anything else we can do about this other than silence the error, which will most likely be the solution we end up going with.
