### ISSUE TITLE
Set maximum image/icon size

### ISSUE THREAD

**Issue by progandy** [dunst-project/dunst#158]
Add configuration options to set an upper limit for the size of icons and images.
This is needed for icon themes (#157) and svg icons (#150) in order to choose a fitting icon size.
For embedded images (#151) there should be an additional option to allow larger images than icons.

**Comment by WishCow** [comment]
I mean no urge, just wondering is there any news on this? Some method of scaling down icons would be really helpful because some notifications take up about 1/3 of screen width currently.

**Comment by Xylemon** [comment]
I'm trying to move over from another notification daemon and this feature would be wonderful to have.

**Comment by michaelherold** [comment]
This would be a wonderful addition. Currently [Guard][guard] notifications are nigh unusable due to [the large size of their icons][icons]. I'm going to check with them to see why their icons are so large, but it seems like this is something that should also be handled at the notification daemon level as well.

[guard]: https://github.com/guard/guard
[icons]: https://github.com/guard/notiffany/tree/master/images

**Comment by adnanh** [comment]
:+1:

**Comment by progandy** [comment]
@michaelherold, as a quick fix you can modify the icons for specific notifications with a rule. Match on "icon" and set a smaller/different icon with "new_icon".

**Comment by Eizen** [comment]
Fixed in 342a235
