### ISSUE TITLE
After locking screen, dunst window can lose its on-top property

### ISSUE THREAD

**Issue by mgraham** [dunst-project/dunst#225]
After I lock the screen and focus another window, the dunst notification window is no longer on top of all other windows, and new notifications are not visible unless minimizing all windows.

Here's what I do to reproduce:
- trigger a notification
- lock the screen
- unlock the screen (at this point dunst's notification window appears as a black box with no contents)
- focus another window (dunst's window now disappears behind the newly-focused window)

After this, new notifications appear behind all other windows.

Maybe the fix proposed in #160 would help here?

(My configuration: goomwwm with kde, dunst master)

**Comment by bebehei** [comment]
Well, there are almost three years in between now. A few releases and nobody is able to really reproduce it.

But I doubt that your issue is actually related to #160 

> ... (at this point dunst's notification window appears as a black box with no contents)

Your box is visible at least at the beginning and it's black. If the box is black, usually dunst has done something wrong (drawing context issues, etc..) and it wouldn't surprise me, that something else goes wrong to make dunst loose it's on top property. Also I wouldn't be surprised if dunst would have shown up as a black box.

Have you actually experienced it in the meantime on a current master?

**Comment by mgraham** [comment]
I am sorry to say I am no longer using dunst - I am spending most of my time on OSX now.  I am happy to have the issue closed.

**Comment by bebehei** [comment]
>  I am happy to have the issue closed.

Then let's do it ;-)
