### ISSUE TITLE
Support for synchronous notification hints

### ISSUE THREAD

**Issue by metakirby5** [dunst-project/dunst#229]
Is it possible to support synchronous notification hints? For example, `-h string:synchronous:ncmpcpp`. I have notify-send run with every song change, and I can't find a way to make the song change notifications "overwrite" each other so there's only one on-screen at a time.

Thanks!

**Comment by Narrat** [comment]
One possebility would be to use dunstify (included with this repo)
With it you can get the notification ID of something and replace this specific ID with another notify.

Not so nice is the fact, that you need some way to store the notification id (like a file in /tmp) if the notify-send thing isn't included in a script, that runs like daemon
I set something like this up, but for using it with notification for volume changes. Previously I got x notifications where it would have made sense to display just the latest and now it's doing that.

Alternatively use mpd-notification for displaying song changes. It runs as a daemon and replaces notifications if a update appears, while the previous one is displayed (I suppose it's mpd, because of ncmpcpp)

**Comment by metakirby5** [comment]
Dunstify works great!

**Comment by tsipinakis** [comment]
Seems like @Narrat 's reply solved your issue so I'm closing this. Feel free to re-open it or open a new one if you need something else.
