### ISSUE TITLE
No character limit with Mumble

### ISSUE THREAD

**Issue by Xylemon** [dunst-project/dunst#248]
For some reason, certain user messages or own messages can be as long as possible in dunst when using it with Mumble. The result is your entire system will freeze till the notification goes away. A great example of this is when someone sends an image in the chat, it displays all the characters that make up the encrypted image (which is thousands of characters).

**Comment by hobarrera** [comment]
Not at all mumble-specific. Just run this script to reproduce this:

```bash
notify-send $(python -c "print('A' * 5000)")
```

Solution is probably to trim messages at some length (or amount of lines, though this may result more complicated).

**Comment by bebehei** [comment]
Well, I think I've created a solution. It limits the length of the single fields in `format_msg`. See #332 

I could fix @hobarrera's example, but I'm unsure what the author's actual intention was. Delivering encrypted images makes no sense, as the notification daemon has no option to decrypt it.

**Comment by hobarrera** [comment]
I'm guessing he didn't mean encrypted, but probably base64 or something like.

**Comment by bebehei** [comment]
So, I tested the initial problem with two mumble-clients:

Mumble interprets the sent image correct and replaces the image with a Unicode icon in the notification body.

Sending from the left client (run as another user) to the right client.
![mumble-test](https://user-images.githubusercontent.com/2073458/27980216-b0fe87b4-637c-11e7-8a9b-6a17ab6825f5.png)

```sh
[bebe:~] % dunst -print
{
        appname: 'Mumble'
        summary: 'Text Message'
        body: 'b2: ￼'
[...]
        formatted: '<b>Text Message</b>
 b2: ￼'
[...]
}
```

So, the initial problem is solved correctly by mumble.

> The result is your entire system will freeze till the notification goes away.

I had issues reproducing it first. But it's not triggerable via `notify-send` on commandline, because the argumentlist is not allowed to get so long to hit the issue. We have to use this python-snippet:

```py
from gi.repository import Notify
Notify.init("App Name")
Notify.Notification.new("A"*10000000).show()
```

Testing with the current master and the proposal from #332, there is a huge difference processing and showing this generated notification. master takes some minutes (and even the python `Notification.new()` throws a TimeoutException`) vs #332 (subsecond).

I would go for #332 to solve this. I'll comment there about the best internal solution.
