### ISSUE TITLE
Newline symbol '\n' never ignored even with "ignore_newline=yes"

### ISSUE THREAD

**Issue by gozhev** [dunst-project/dunst#293]
Regardless of "allow_markup" state and "ignore_newline" state, newline symbol '\n' never ignored in notification summary and body.
version: v1.1.0-152-g3f5257f

**Comment by tsipinakis** [comment]
Woops, sorry about that. I assume that was because I removed the `allow_markup` option a bit _too_ quickly. It was changed into `markup` in 4e1b97f3ccc35672d5588be1b4f801b3532358c6 but didn't do anything about backwards compatibility and probably broke a lot of git users configs in the process.

Can you check if the issue still exists with 42a641c728c7fb7ace0b3aa126fded0179b7bde4?

**Comment by gozhev** [comment]
I think it's still here. The only working combination to remove '\n's I found is "markup=no" alongside "ignore_newline=yes" ("markup=strip" is not working).

I think it would be more logical if "ignore_newline=yes" option would force removing of both '\n' and '<br />' symbols regardless of "markup" option.

**Comment by Eizen** [comment]
@gozhev I've pushed a fix to the branch `fixignore`. Would you mind testing?

**Comment by gozhev** [comment]
It fixes the issue, thanks!
