### ISSUE TITLE
Optionally handle "transient" notifications

### ISSUE THREAD

**Issue by ohque** [dunst-project/dunst#310]
Desktop Notification Specification defines a `transient` hint:

>When set the server will treat the notification as transient and by-pass the server's persistence capability, if it should exist.

https://developer.gnome.org/notification-spec/#hints

Applications that use this hint are media players (e.g. on song change), as well as others like NetworkManager.

There could be a `history_ignore_transient` option in dunstrc which would work in the same way as `history_ignore` already does - although being a global option.

**Comment by tsipinakis** [comment]
I have 2 objections to this:
 1. The notification spec also defines 'persistence' as

    > Notifications will be retained until they are acknowledged or removed by the user or recalled by the sender. The presence of this capability allows clients to depend on the server to ensure a notification is seen and eliminate the need for the client to display a reminding function (such as a status icon) of its own. 

    Dunst does not have such a feature, we have a notification history where one can recall previous notifications to check what happened while you were away or weren't paying attention, but we don't have a way to remind of missed notifications or keep notifications up until they are acknowledged (setting timeout = 0 would be a way to do it but that's mostly a side-effect of the timeout setting and depends largely on the server config).

2. At this point having `history_ignore_transient` and `history_ignore` starts to become a case of featuritis or at least having way too many similar knobs that users would have to dig a bit to find out the difference between them.

**Comment by hobarrera** [comment]
When AFK, notifications are retained with a timer so I can see them when I come back.`transient` ones could skip this.

**Comment by tsipinakis** [comment]
Closed via 16bbde5bf3a7ef9b1c6f066b3cc292a64988b935

**Comment by tsipinakis** [comment]
I'd like to bring this topic up again, after implementation transient notifications are handled as follows (from #343 )
> * ignored automatically in history
> * removed from stack, even if X is idle.

From a brief interaction on iRC seems that the first point in ignoring these notification from history can cause some confusion since everyone would expect all notifications to be there unless something is blocked manually.

Furthermore if you do a simple [code search](https://github.com/search?p=1&q=transient+notify&type=Code&utf8=%E2%9C%93) on github there are a *lot* of clients setting the transient hint on notifications that I definitely wouldn't want to miss from history.

So I propose the first behaviour of this is removed by default and can optionally be added as an example rule in the dunstrc to be enabled if the user requires it. Although retracting that might be a bit awkward now since the change has already been in a point release but not much we can do about that currently.

**Comment by bebehei** [comment]
I agree with you. I guess we have to release 1.3.1 and revert the `transient` => `history_ignore` rule.
