### ISSUE TITLE
Setting width through notify-send

### ISSUE THREAD

**Issue by therockmandolinist** [dunst-project/dunst#313]
I'm not sure if this is possible, but it would be nice to have the option to set the width through `notify-send`.

Basically, I _do_ want fixed width without shrink for most notifications, since I like how text is wrapped and width stays consistent for shorter notifications. In some specific cases, however (displaying the output of `df -h` for example), I'd like dunst to act as if width was set to 0, so it doesn't wrap the formatted output weirdly. 

As far as I can tell, right now all I can do to mitigate this is set width=0 for all messages, which doesn't get me that nice text wrapping or padding when I do want it.

**Comment by tsipinakis** [comment]
We try to follow the [GNOME Notification Specification](https://developer.gnome.org/notification-spec/) where possible which doesn't support configurable notification sizes.

That said, sounds like matching rules could probably be expanded to do what you want. Specifically setting up a rule that matches the notification that requires the extra width and overriding the geometry on it. But due to the way dunst currently handles notifications this would require a significant refactor of the display code.

There is already an issue open about that, #265, thus I'm closing this as a duplicate.
