### ISSUE TITLE
Format inside notification contents are being expanded as in format

### ISSUE THREAD

**Issue by Anachron** [dunst-project/dunst#322]
Using `%I` inside the message body expands `%I` which is not supposed to happen:

> 4:23:42 PM - nikos: Also, you are also using a second bug here which is that %I etc values get expanded in the body of the message. This hasn't been fixed yet but might get to it soon.

**Comment by tsipinakis** [comment]
Some extra info:

This happens because we expand all format strings sequentially in [`notification_init`](https://github.com/dunst-project/dunst/blob/8b74a756c2a1eaa95120ce8fcf56540f1f29cbb5/src/notification.c#L307). The best solution would probably be to have a `start_position` pointer as a parameter to `notification_replace_format` in order to skip over everything that has been replaced previously.

On another note, we should first find out if people are relying on this behaviour. If so, while it shouldn't be a default since it is not part of the notification specification, we should consider adding an option that allow all format strings to be expanded from the notification contents in this way.

**Comment by Anachron** [comment]
@tsipinakis as you know I'm using this as a workaround for grouping notifications together using `notify-send -i 'mystuff' 'Test: %I'`.
