### ISSUE TITLE
Dunstify not available

### ISSUE THREAD

**Issue by silentwarrior** [dunst-project/dunst#326]
Hello,

I installed Dunst version 1.1.0 but I dont have access to dunstify. It seems this was a bug before but has been fixed for version 1.1.0 however I still do not have access to it from my console.

I am running ubuntu 16.04 with i3wm if that matters.

Thank you

**Comment by tsipinakis** [comment]
That's because it's intended as a debug tool and hence it's not installed by default. For sending notifications from the command line `notify-send` can handle most cases, and you can compile dunstify yourself if you need the extra functionality.

There are plans to develop a command line utility for dunst as part of #284 which might also include some of the more advanced features it has.
