### ISSUE TITLE
Critical notifications doesn't disappear

### ISSUE THREAD

**Issue by dikiaap** [dunst-project/dunst#362]
I have a problem about critical notifications.

I just checked every commit before PR https://github.com/dunst-project/dunst/pull/352 is merged, all is well.
And now I use https://github.com/dunst-project/dunst/commit/66fceb9661ef24ed98d79a18fd245c68ed77dfc8 untill [new commit](https://github.com/dunst-project/dunst/commit/3c257eaeb72c7d64d34ff040fe68219068ad4c30), I have a problem in critical notifications that can not be closed.

To solve my problem, I should change the `timeout = 0` to `timeout = 10` or some more than 0.
[My config](https://github.com/dikiaap/dotfiles/blob/master/.dunst/dunstrc#L53).

**Comment by tsipinakis** [comment]
As I mentioned in a [comment] in #352 this is because `iter` is not being incremented if the current iteration of the `check_timeouts` loop is skipped. Refer to the following piece of code:
https://github.com/dunst-project/dunst/blob/99c74b8703739257bb52ac55b4fe97552eed2cf8/src/dunst.c#L60-L82

Solution is to simply move the `iter = iter->next` assignment above the loop logic.

**Comment by tsipinakis** [comment]
Fixed in eb0a0f860274f0058e3124c8ccd1f007ef0222c9

**Comment by bebehei** [comment]
shit, this is worth a real facepalm 🤦‍♂️. Sorry for that. That's my fault!
