### ISSUE TITLE
dunstify doesn't keep notifications

### ISSUE THREAD

**Issue by dasJ** [dunst-project/dunst#415]
When specifying the timeout with `-t`, the source code of dunstify tells me that a value of 0 keeps the notification forever, > 0 for the amount of milliseconds and -1 for the server default.

However, when specifying 0, the notification immediately disappears.

**Comment by tsipinakis** [comment]
This is... bizarre. The issue is definitely in dunstify - dunst is receiving a `CloseNotification` command from it.

Running dunstify under gdb shows that the signal is emitted after calling `notify_uninit` before exiting. Not sure how or why.

**Comment by tsipinakis** [comment]
Relevant code in libnotify `notify_uninit`:

https://github.com/GNOME/libnotify/blob/43aac613f1c2a56aa672c36c157c9b8eb193ac25/libnotify/notify.c#L200-L207

Looks like it's purposefully removing notifications without timeout - but why isn't notify-send running into this?

**Comment by bebehei** [comment]
I've got it. The problem is not at `notify_uninit`, it's that [we do not free the notification](https://github.com/GNOME/libnotify/blob/master/tools/notify-send.c#L280). Therefore `notify_uninit` goes over every notification and closes it again.

While examining this looked quite bogus, because dunstify also sent the CloseNotification signal.

PR incoming.

@dasJ Thanks for finding such a weird bug.
