### ISSUE TITLE
[Question ]Dunst notification when running a script which executed as root ??

### ISSUE THREAD

**Issue by narutowindy** [dunst-project/dunst#436]
what i have done is

    $su 
     #./script.sh
     .... 
     ....
    notify-send 'Done ....' 'ckeck this out.'
    
no Notification is shown. (Dunst is running as Normal User,  i3 config )

**Comment by bebehei** [comment]
Hey @narutowindy 

There is the variable `DBUS_SESSION_BUS_ADDRESS`, which is defined in your environment, when you're a normal user. By this variable, `notify-send` knows, where to connect to the notification daemon.

So you have to take it with you, like this.

```
sudo --preserve-env=DBUS_SESSION_BUS_ADDRESS su
```

Alternatively, you could also do an `echo $DBUS_SESSION_BUS_ADDRESS` and manually export it in your root shell.

---

But that's not all. `notify-send` will send the notification, but DBus will reject it then in your session. Because your users' normal UID does not match root's UID. It's a security measure of DBus.

So in your shell, you have to send the notification as your calling user. You have to invoke notify-send this way:

```
su <username> -c "notify-send summary body"
```

---

We should probably add this to the FAQs.

**Comment by bebehei** [comment]
The previous comment is still right, but it's not **the easiest** solution.

Define this alias in your rootshell and you can use notify-send as usual:

```
alias notify-send="sudo -u <USERNAME> DISPLAY=:0 notify-send"
```
