### ISSUE TITLE
Dunst version and changelog ambiguity

### ISSUE THREAD

**Issue by anbenson** [dunst-project/dunst#511]
### Installation info
- Version: 1.2.0-279-gf8538c9
- Install type: git
- Distro and version: Linux 4.16.5-1-ARCH

I'm confused by the versioning scheme used in dunst.

According to the changelog and release notes (how come we have both?), the most recent dunst is 1.3.0. This is backed up by the Makefile / dunst -v as long as you didn't install from git.

https://github.com/dunst-project/dunst/blob/master/CHANGELOG.md
https://github.com/dunst-project/dunst/blob/master/RELEASE_NOTES
https://github.com/dunst-project/dunst/blob/master/Makefile

According to the website changelog, the most recent dunst is 1.3.1. The Arch Linux package also says this, though of course that's not authoritative.

https://dunst-project.org/changelog/

According to dunst -v if you install from git, the most recent dunst is 1.2.0. I'm guessing that's just a bug due to not git tagging the 1.3.0(1) release(s).

Could you shed some light if any of these things are things that should be fixed?

**Comment by bebehei** [comment]
> I'm confused by the versioning scheme used in dunst.

Ouch. We released software, and updated basically every link *outside* the repository, but all links _inside_ the repository were left stale. :see_no_evil: 

> According to the changelog and release notes (how come we have both?),

The changelog should track all changes with a short note. Nothing more. While the release notes should be a brief document handed with a release summarizing the most important changes and describing what to do. The release notes is an important document for people not involved in the code.

> According to dunst -v if you install from git, the most recent dunst is 1.2.0. I'm guessing that's just a bug due to not git tagging the 1.3.0(1) release(s).

Err, something went south there. Do you have all tags in your local gitrepo? We tagged all releases. I know, that the `v1.3.0` tag is not an annotated tag, and therefore `git describe` and `git describe --tags` will report different things. But the [`v1.3.1` tag](https://github.com/dunst-project/dunst/releases/tag/v1.3.1) should be fine again.

**Comment by anbenson** [comment]
> but all links _inside_ the repository were left stale

Can I help to fix that, or are you already on that? The ones I'm aware of are the changelog, release notes, and the Makefile, but I don't know if there are more.

Good to know about the difference between the release notes and changelog, thanks.

> Do you have all tags in your local gitrepo?

TIL about `git fetch --tags`. Yep, my local repo didn't have the new tags. After downloading them, I now get
`$ git describe`
`v1.2.0-279-gf8538c9`
`$ git describe --tags`
`v1.3.0-61-gf8538c9`

Is this expected? It sounded like from what you said that they should both report v1.3.1. Looking through the git log, it looks like that's because the v1.3.1 tag branched off. But I think the git version should still report v1.3.1?

**Comment by bebehei** [comment]
> Is this expected?

Actually no. But the root cause is clear.

> Can I help to fix that, or are you already on that?

Well, I guess the person, which fits best for this job is @tsipinakis. I'd like to have a statement, why he didn't consider merging the `maint` branch back to `master`. If this was carelessness, then I'd go on and fix it now, but usually @tsipinakis works very carefully. And therefore I'd prefer to wait for a statement first.

This may take some time as he's currently busy. But there's no immediate danger approaching which requires immediate action.

**Comment by tsipinakis** [comment]
> Yep, my local repo didn't have the new tags

That's weird, `git-fetch` should fetch tags for branches that "you are interested in" as the git docs say. I wonder if this is an annotated vs not tag issue?

> Can I help to fix that, or are you already on that?

> I'd like to have a statement, why he didn't consider merging the maint branch back to master.


That was actually a conscious decision the reason being that the `VERSION` variable in the Makefile is only a fallback and is being overridden by the latest git tag, so while merging `maint` would update that for people building outside of git it would be a mess internally since:
* Changelog would mention 1.3.1
* Building outside of git (i.e. downloading a tarball from github) would report version 1.3.1
* But building from git would report version 1.3.0

I figured that it's best to leave it like this for now and for the future create tags with only the major and minor version (e.g. 1.3) and leave the patch number to exist only in the `maint` branch. Maybe you have a better idea on how to handle this?

I should've opened an issue about it then but not sure why I didn't. Thanks for bringing it up.

**Comment by anbenson** [comment]
I'm unsure about the tags issue - my best explanation is that I had two copies of the repo downloaded and I may have synced one but not the other and maybe foolishly ran different commands in each? And then one of those repos might have been downloaded from my fork? Either way I don't think there's a problem with the tags in this repo since after downloading it works as expected.

So I don't think I understand - if you merge `maint` into `master`, won't building from git report v1.3.1 since the latest git tag as returned by `git describe --tags` will be v1.3.1? Then it seems like all sources would report v1.3.1.

**Comment by tsipinakis** [comment]
You're right, I was under the impression that because I cherry picked the commit into maint git would complain but after googling around that isn't the case. Apparently I didn't even bother to test it back then.

I'll go ahead and merge `maint` which should resolve this.
