### ISSUE TITLE
Not correctly wrapping text with shrink enabled.

### ISSUE THREAD

**Issue by ramblingenzyme** [dunst-project/dunst#518]
Setting a max width on notifications, along with shrink and word_wrap seems to wrap content based on a notification's min width instead of the width of any already present notifications.

Center aligned
![scrot](https://user-images.githubusercontent.com/5336472/41283395-d016d756-6e79-11e8-8308-f5c6ecec43f2.png)

Right aligned
![scrot](https://user-images.githubusercontent.com/5336472/41283481-098f6246-6e7a-11e8-804c-e76974fa29ca.png)

### Installation info
- Version: 1.3.2
- Install type: package
- Distro and version: Void Linux

**Comment by bebehei** [comment]
Thank you for opening the bugreport. I can reproduce it in some way:

```
alias callA="notify-send 'yaxg ' 'Saved to /tmp/scrot.png'"
alias callB="notify-send 'yaxg' 'Copied to clipboard'"
```

```
# necessary parts of the dunstrc:
startup_notification = no
word_wrap = yes
shrink = yes
geometry = "150x5-30-30"
```

> $ callA && callB

![screenshot from 2018-06-12 13-05-11](https://user-images.githubusercontent.com/2073458/41286930-68027400-6e41-11e8-84c5-49418f2afa5e.png)

> $ callB && callA

![screenshot from 2018-06-12 13-05-31](https://user-images.githubusercontent.com/2073458/41286944-725c018c-6e41-11e8-9caa-4c1c3ea1e54a.png)

**Comment by bebehei** [comment]
@ramblingenzyme The only thing I still don't understand: Why is the `yaxg` part of your notification so misaligned. Have you added some spaces? Have you sent an icon with the first notification, but not with the second?

Can you please shed some light on it?

**Comment by ramblingenzyme** [comment]
Sorry, the first screenshot is using center alignment and the second is using right alignment.

**Comment by tsipinakis** [comment]
Thanks for the report! Took me some time to finally understand what's going on: there is a bug here but it doesn't have to do with word wrapping, `scrot.png` is in the next line because there just isn't enough space to put it in the first one with your current width limit.

The bug is how we handle alignment and `shrink` together:
After the text of the first notification is wrapped it brings it under the width limit and the window is shrinked a bit. Then the second notification comes along, which while is not long enough to be wrapped it is longer than the wrapped text of the first one so it re-expands the window.

We're skipping a step after that processing to update the first notification to re-align with the new window dimensions.

You've managed to find a really weird edge-case. A quick fix would be to increase your geometry width by 50 pixels or so but it's obviously temporary as it only shifts the issue to longer notifications.

---

As for fixing it permanently, this bug lies in one of the most confusing parts of the code that handles dimension calculations which is due to a refactor. I personally would wait until after the refactor to fix this since it's an edge case and it would add a lot more noise currently but would gladly merge a fix if someone else is willing to put forward the work to fix it themselves. Do you agree @bebehei ?

**Comment by bebehei** [comment]
> I personally would wait until after the refactor to fix this since it's an edge case and it would add a lot more noise currently but would gladly merge a fix if someone else is willing to put forward the work to fix it themselves. Do you agree @bebehei ?

Well, I agree. It isn't urgent enough for a hotfix. But I wouldn't ignore it during the ongoing refactoring either.

I'd use the refactoring to create an architecture, which rules out this type of bug.

**Comment by ramblingenzyme** [comment]
Thank you for being so quick and polite about this. No issue with waiting for this to be fixed when most appropriate. Thank you for the great software as well.

**Comment by tsipinakis** [comment]
The refactor for this part of the code isn't done yet and this is a fundamental issue with the algorithm used so it can't be fixed quickly.

I'm bumping this to 1.5 to unblock the release of 1.4.

**Comment by fwSmit** [comment]
@ramblingenzyme could you try if #855 fixes your issue? It reworks the way window dimensions work and should fix any lingering bugs
