### ISSUE TITLE
Newline in summary shows incorrectly

### ISSUE THREAD

**Issue by jubnzv** [dunst-project/dunst#524]
### Installation info
- Version: `v1.3.2-118-g74bbc96`
- Install type: ` package from sid | manually`
- Distro and version: ` Debian 9.4`

I got stuck with strange behavior of `\n` when use latest version of dunst (git sources or sid package). There is no similar issue in Debian stable official package.

The `\n` symbol in first argument of `notify-send` shows incorrectly. Here is screenshot with default `dunstrc`:

![2018-06-27-195410_1366x768_scrot](https://user-images.githubusercontent.com/12023585/41989086-cd283fac-7a46-11e8-976a-2ec986220924.png)

But newline from second `notify-send` works as it should:

![2018-06-27-201751_1366x768_scrot](https://user-images.githubusercontent.com/12023585/41989288-7228e20e-7a47-11e8-8a83-b79d254931ad.png)

**Comment by tsipinakis** [comment]
Before, we used to explicitly convert all `\n` into actual newlines which is the old behaviour you are familiar with, but in #299 this behaviour was removed as it seemed (to me) that you can simply send a literal newline when sending a notification. Apparently this isn't the case.

The weird thing is, the body still works but not the summary. Some testing shows that `notify-send` sends actual newline characters for the body but sends `\n` for the title:
```
(gdb) break dbus.c:276
notify-send 'test\ntest' 'Foo\nbar'
(gdb) p summary
$1 = "test\\ntest"
(gdb) p body
$2 = "Foo\nbar"
```

Even weirder, `dunstify` escapes both:
```
(gdb) p summary
dunstify 'test\ntest' 'Foo\nbar'
$3 = "test\\ntest"
(gdb) p body
$4 = "Foo\\nbar"
```

I have a feeling this is some implementation detail in libnotify or dbus.

**Comment by tsipinakis** [comment]
I got some time to look into this, it's apparently by design in `notify-send` that only the body gets escape characters replaced. We should match that in dunstify as well.

- [ ] TODO: Pass the notification body through `g_strcompress` in dunstify

---

@jubnzv Going back to the topic of the issue what's your usecase for this? I can't think of many uses for something like this.

A workaround is available using bash like so:
```
notify-send 'Foo'$'\n''Bar' 'Body'
```
this may or may not work depending on how you want to use it.

**Comment by jubnzv** [comment]
@tsipinakis Really I have some notifications with `\n`-summaries in few small scripts on localhost. I have already changed their format after update, so there are no any problems for me. Thank you for your reply!

**Comment by TJokiel** [comment]
Hi team,

This issue prevents me from migrating to newer dunst version. I need to be able to use newline in the summary (do not use the body at all in my scripts). 

Which dunstify syntax i should use to achieve this?

Tried:
dunstify "test\ntest"
dunstify "test\\ntest"

and it does not work.

**Comment by tsipinakis** [comment]
If you're using bash you can use the `$'string'` to force a newline.

`dunstify $'test\ntest'` (note the singlequotes)

**Comment by TJokiel** [comment]
Unfortunately single quotes would require additional single quotes as i have variables in the summary. Things are getting overly complicated for my use case (perhaps it would be easier to just stick to older dunst version).

Unless you have a plan to bring the old behavior back? Maybe as an option in the config?

I see there is already:

# Ignore newlines '\n' in notifications.
ignore_newline = no

but toggling yes/no has no effect in my tests. Probably i'm using it incorrectly.

**Comment by tsipinakis** [comment]
> I see there is already:

You might have misunderstood the problem, dunst handles actual newline characters as usual by default (which is what this setting controls). The behaviour that was removed was converting the string `\`, `n` to a newline. Because (and I still stand by this) this is not the servers job, it's the client that should send the character that it wants to be displayed and not an escape sequence.


notify-send and recently added to dunstify passes the body through `g_strcompress` which does such substitutions but is called [only on the body for some reason](https://sources.debian.org/src/libnotify/0.7.7-3/tools/notify-send.c/#L204).

---

> perhaps it would be easier to just stick to older dunst version).

For me at least this wouldn't be a solution, as breaking workflows (and breaking them in a non-major release which was a mistake in the first place) without a suitable replacement is a detriment.

I'm hesitant to fix this on the server for the reason mentioned above that leaves one more solution I can think of: Improve the client.

Some suggestions on what we could do:

* Add a flag to dunstify to also handle escape sequences in the summary
* Make it escape both body and summary by default (but we then are not mimicing notify-send 100% as was originally intended).

Any feedback/other ideas on this?


---

I'm also pinging @bebehei in case you have any feedback here.

**Comment by bebehei** [comment]
I have to make a confession first: I'm not a fan newline support in the notification summary. (I'm not even a fan of newline support in the body. But yeah, it makes more sense and there exist good use cases in the body).

Please fix your scripts and do **not** use a newline in your summary. It's absolutely counterintuitive to merge and place some content into a single field, while you have got two designated ones available. [Even the standard says, that you should use only a single line](https://people.gnome.org/~mccann/docs/notification-spec/notification-spec-1.2.html#id2780838).

On the one hand side, we definitely broke "reverse compatibility". But what do you define as "reverse compatibility"? I wouldn't consider undocumented features as features to save for "reverse compatibility". And in this case, even the maintainer had been unaware that this could have been a feature.

I consider the replacement of `\n` in the summary a bug, which nobody had been aware of during development. Now we fixed it. Yes, it broke. And some did rely on this bug and thought it was an actual feature.

TBH this is desperate. I just recently had a similar issue. I had a parameter function, which had actually no effect and just sucked the value, but I set a value for this parameter during creation of the code and didn't get this was a bug. Fast Forward half a year: Software update. It made bang. The parameter was used now. But I never had been able to test it. And I wasn't aware that I never tested the parameter.

And I have to say, yes, this is shit. But I as a maintainer would rather choose the "correct" :tm: choice than fitting anyone's usecase. This makes things better in the long run rather than for short time.

For me, this seems to be like somebody is using multiple working copies for one's git repository to use multiple branches, because CVS&SVN had a separate folder for every checked out branch. Absolutely counterintuitive.

**Comment by TJokiel** [comment]
My scripts are in the production so i wont be touching them till i really have to. 
In this case i'll use an older version of the dunst package until i stops working.

Thank you for your time, for this case is closed (for now).

**Comment by tsipinakis** [comment]
Apparently I never resolved this issue:

As @bebehei correctly said above,

Admittedly we broke backwards compatibility by mistake or otherwise here but this was an undocumented feature that went against the standard. And with this change dunstify now behaves consistently with notify-send which only allows newlines in the body.

---

Workarounds exists, if this is _really_ needed in some case dunst will still accept a literal newline character in the summary
e.g.
```bash
notify-send "Summary line 1"$'\n'"Summary line 2" "Body"
```
