### ISSUE TITLE
Redraw problem

### ISSUE THREAD

**Issue by kajzersoze** [dunst-project/dunst#539]
I have a situatiuon where I download one image into one file and then use that image to display notification as icon, when I download some other image into the same file to display second notification, first notification gets redrawn with the image from the second.
That creates a problem for me.
Is it really necessary to redraw first notification if it's already displayed when drawing second notification ?

**Comment by tsipinakis** [comment]
> Is it really necessary to redraw first notification

The problem isn't with redraws, those happen frequently and for many reasons (i.e. something obstructed dunsts window for a moment and X asks us to redraw, we need to re-sort the notifications as another one comes through etc). We opt to redraw the entire thing as the performance hit is minimal and it simplifies out code a lot.

---

The problem here can be immediately solved by using raw icons. If you're using `dunstify` you can use the `-I` flag but notify send doesn't support them unfortunately.
This essentially sends the contents of the icon as part of the notification rather than saying "read this file" to dunst.


That said, there is probably a feature request (maybe bug?) here, which is that dunst re-reads the icon every time it re-draws, when we optimize the drawing code we should maybe opt to keep icons around rather than re-reading them.

**Comment by kajzersoze** [comment]
Wasn't using `dunstify` but now I did, `-I` flag solved the problem I was having.

Thank you very much !
