### ISSUE TITLE
Format of the message color issue

### ISSUE THREAD

**Issue by kajzersoze** [dunst-project/dunst#546]
There seems to be a problem with markup, I'm not sure where exactly is the problem, idea was to have separate colors for title and the body of the notification. I came up with this in the config file

`format = "<b><span foreground='#fcaf3e'>%s</span></b>\n%b"`

it works fine, however sometimes I did notice one problem with it but I didn't care enough to bother with it until now, problem is that in some cases title had the same color as the body, in this case white. Found out that if in the body of the message is the `&` symbol that would happen.

So, for example `dunstify "Testing" "Example"` works fine.
But `dunstify "Testing" "Example & More"` gives the problem described above.

Maybe it's escaping strings wrong or something like that, maybe there are more symbols like ampersand which would produce the same problem, I'm not sure, but I'm sure of this one.

Or maybe I'm doing something wrong with the format in the config file.

**Comment by tsipinakis** [comment]
The color issue is happening because, from dunsts perspective, you're sending an invalid notification, so the markup parsing fails and we fall back to stripping it off and displaying it in plain text as best as we can. (There should be an error in stdout)

If you have `markup` enabled in the config, it's the responsibility of the client to send us properly escaped text. The correct way to do this is, for example `dunstify "Testing" "Example &amp; More`. This isn't done on dunstify (and notify-send) purposefully as one might want to send markup from the command line.

The [notification spec](https://developer.gnome.org/notification-spec/) is really vague about this, it specifies a few markup tags but no reference on escaping so dunst (and other clients) implicitly include HTMLs `&char;` character escape feature.

---

I'll mark this as a bug because we can do some more smart parsing with `&`-escapes, hell a regex would work. But there are still areas that will make it fail, for example `<`, `>` characters will either result in the same error, or it will make the parser eat up parts of the text due to it being an invalid tag.

**Comment by kajzersoze** [comment]
I see, thanks for the explanation.

Until (and if) it lands in the dunst code I'll try to escape it in the code I'm using.

It's not a big thing but I thought I should report it anyway.

**Comment by tsipinakis** [comment]
If you do not care about markup in the summary/body of the notifications, setting `markup = no` in the config would resolve your issue without escaping it. (Obviously markup inside `format` still gets processed.)

**Comment by kajzersoze** [comment]
Resolved indeed, I had `markup = full` previously.

I'll leave closing of this issue to you then, since it's marked as a bug.

**Comment by kajzersoze** [comment]
Actually I had to go back to `markup = full`
It's better to have mentioned color problem but with escaping.

**Comment by tsipinakis** [comment]
@kajzersoze Can you give an example notification that doesn't work? Works fine with my tests.

**Comment by kajzersoze** [comment]
So, in duntrc 
`markup = full`
`format = "<b><span foreground='#6495ed'>%s</span></b>\n%b"`

this works, different colors for title and the body
`dunstify "Test Example" "Test Example More"`

but this one changes the color of the title to the color of the body
`dunstify "Test Example" "Test Example & More"`

the only difference is added `&` in the body of the text

**Comment by tsipinakis** [comment]
Just tested your example, it works fine on my end.
What does `dunst --version` say? Can you post the entire dunstrc?

**Comment by kajzersoze** [comment]
```
$ dunst --version
Dunst - A customizable and lightweight notification-daemon v1.3.2-146-ge09e299
```

I am restarting dunst after changes, but here is `dunstify -s` anyway
```
name:dunst
vendor:knopwob
version:v1.3.2-146-ge09e299
spec_version:1.2
```

`dunstrc`
https://bpaste.net/show/06fc0730191d

**Comment by kajzersoze** [comment]
It was a mistake on my part, I apologize.
It works now :)

Thanks!
