### ISSUE TITLE
How can you make the dunst window transparent and exclude the text

### ISSUE THREAD

**Issue by catzybluphish** [dunst-project/dunst#573]
When I set the `transparency = x` it'll make the entire window transparent which includes the text, borders, images, etc. Of course, I only wanted the background of the window to be transparent but don't know how. I've tried setting the `frame_color = #ff00ff00` to have opaque alpha but that didn't work either.  I'm using Arch, bspwm and compton. [Current config](https://pastebin.com/ypsigHsx).
![arch_blur](https://user-images.githubusercontent.com/40843060/49492030-50df4500-f8a2-11e8-9178-e9d36964681e.png)
Here's a nice desktop of what I want to achieve.

**Comment by tsipinakis** [comment]
Oh, this issue fell through the cracks sorry!

This is not currently possible with the current features, I guess this falls under the category of implementing RGBA support which has been a long open issue (#289)

**Comment by bebehei** [comment]
We may be able to solve this. I'm wondering why I haven't answered this yet. I thought I answered it already.

Actually I'd like to dump the opacity setting, too. I'd like to shift this to RGB**A** values.  But I had a failed attempt in #344. In there, I used rgba values, but I instructed cairo to draw over our own drawn surface instead of incorporating the lower window's surface.

In between the PR and now, over 1.5 years passed and I found [`cairo_operator_t`](https://cairographics.org/manual/cairo-cairo-t.html#cairo-operator-t). Maybe in combination with a call to [`cairo_set_operator`](https://cairographics.org/manual/cairo-cairo-t.html#cairo-set-operator), we could handle this and finally have RGB**A** values.

**Comment by bebehei** [comment]
@tsipinakis Do you have any knowledge if this correct, what I'm telling here? If it's really the case how I outlined it, it should be super easy actually. And I wonder why it hasn't been implemented yet.

**Comment by SpaceboyRoss01** [comment]
For now, if you're using compton you can just add `"90:class_g = 'Dunst'"` to your `opacity-rule` section. This will make the notifications 90% transparent.

**Comment by bebehei** [comment]
There's an overall `opacity` option in dunst itself. Same effect, but no speciql compositor needed. But this doesn't cover the font (which is this bug's actual feature request).

**Comment by tsipinakis** [comment]
Implemented with #717, not all color strings support transparency.
