### ISSUE TITLE
Override action

### ISSUE THREAD

**Issue by marcelo140** [dunst-project/dunst#577]
I didn't find any way to override the action of a notification. For instance, my music player provides no action but I would like to add a new action that searches for lyrics. Is this behaviour possible?

### Installation Info

- Version: Dunst - A customizable and lightweight notification-daemon 1.3.2 (2018-05-06)
- Install type: Official Arch Linux package
- Distro and version: Arch Linux 4.19

**Comment by tsipinakis** [comment]
There is no such option because actions are not something dunst does by itself, the client sends us a list of actions to display to the user and if one is picked we respond back to the sender with the name of the action and leave it up to them to do all the logic.

To do what you're asking you will need to implement this in your music player and not on the daemon/
