### ISSUE TITLE
Cleanup unused git branches

### ISSUE THREAD

**Issue by bebehei** [dunst-project/dunst#583]
Can we delete all the old branches in the repository please?

- `master`
- <del>`test-circleci`</del>: Why is there a circleci branch? I thought I've made all changes on my own remote?
- `refactor-outputs`: It got mentioned in the wayland discussion (#264). What's the feature of it? Don't we want to merge it then?  
- <del>`refactor-drawing`</del>: Obviously merged.
- `maint`: Is this our 1.3.x release branch?
- `centering`: I've got some dark memories about a merged PR, which didn't land on master branch: #316 
- <del>`drop-gtk`</del>: Pretty sure, that this commit (maybe in another incarnation) is already merged
- `next`: Is this our next branch? So our dunst 1.x incompatible things would go there?
- <del>`error_handling`</del>: I'd consider it useless code now.
- <del>`patches_yuri`</del>: Functionality already implemented.
- <del>`debian`</del>: Well, these are the changes for the debian package. No interest to hold them.
- <del>`0.3.1`</del>: Obviously, this should be a tag.
- <del>`light`</del>: Useless in the meantime.

This is an overview of **all** branches. I've striked all the old branches, which I would delete.

**Comment by tsipinakis** [comment]
* `refactor-outputs`: This is the output abstraction, when we, or someone else, decides to implement wayland support it's a reference on how to abstract away X11 calls. I also tried to use it for #569 which is currently stuck in a limbo.

* `main`: Is the branch for our point releases as you said

* `centering`: Ouch, that was left there for a while and no-one picked it up because we are waiting on #336, IIRC I didn't want to introduce a new setting since we're planning on changing it. Maybe look into partially implementing the `origin` part somehow to get it out of the way?

* `next`: As you said, the backwards incompatible changes, currently only contains #298 (we should rebase that, there's probably a ton of conflicts by now).

As for the rest, I agree without your points they can be deleted.

**Comment by bebehei** [comment]
Deleted the old ones.

I forgot `feature/382-reload-dpi` in this list. What about this? Actually it looks promising. But I'm not able to reproduce it. I haven't got a hidpi display.

**Comment by tsipinakis** [comment]
I forgot about that too. Reading the referenced issue says it was waiting for the drawing refactor but we never touched it since. It could be worth looking at.

**Comment by bebehei** [comment]
So, as there is #382 covered, I think we can finally remove the branch `feature/382-reload-dpi`, which blocked this issue.
