### ISSUE TITLE
How can I make dunst run as a system service?

### ISSUE THREAD

**Issue by ackerleytng** [dunst-project/dunst#591]
### Installation info

- Version: `1.3.2-334-gfb`
- Install type: `manually`
- Distro and version: `Centos 7.6`

Centos 7.6 does not have support for `systemctl --user`, and they don't plan to support it https://bugs.centos.org/view.php?id=8767

Any tips on how I would go about making dunst run as a system service, and still allow user processes to send notifications to dunst?

So far, I've been able to do `sudo dunst`, and `notify-send foobar` works as expected.

**Comment by bebehei** [comment]
At first, `dunst` is a DBus service. And in DBus services, there is a differentiation between user and system services (there's an extra system bus and session bus).

Given by the architecture and goal of your program, it either serves or queries the system bus or the session bus. But it can't do both.

With dunst, you show the user's notifications. So there is no point, using the system bus. We have to use the user-specific session bus.

----

So, how do you start it?

- `sudo dunst` is always the wrong solution.
- start dunst in your setup script. `dunst &` in your xinitrc or `exec --no-startup-id dunst` in your i3 config.
- Mostly you don't have to start dunst, because dbus did it: Usually the setup places a file in `/usr/share/dbus-1/services/org.knopwob.dunst.service`, where it tells dbus, that it should start dunst automatically, when some other programs require the `org.freedesktop.Notifications` service. So a simple `notify-send a` should suffice to start dunst.
    - If notify-send fails, there might be another problem.
    - If the notification gets displayed by another daemon and not by dunst, you might have to remove the other daemon.

**Comment by bebehei** [comment]
For further questions, just ask them here.

**Comment by ackerleytng** [comment]
Thanks for the quick response!

I do have the file `/usr/share/dbus-1/services/org.knopwob.dunst.service`, but doing `notify-send a` does not start dunst.

When I manually start dunst, like `dunst -print` in one terminal window, `notify a` in another window does not cause any popups, and neither does dunst print anything.

There is a `dbus-daemon --system ...` on my process listing, but when I strace that, nothing happens when I use `notify-send a`. Is that because that dbus-daemon is the system one and not the user one?

I tried stracing all the dbus-daemons running on my system (some of them have the path `$HOME/.pyenv/...../anaconda3.../dbus-daemon --syslog --fork ...`) and none of them respond to `notify-send a`

**Comment by ackerleytng** [comment]
I adjusted my .xinitrc according to https://github.com/dunst-project/dunst/issues/238 and now when i run dunst, I'm getting `Cannot connect to DBus`.

I saw this, how should I check these?

+ dbus packages are really installed = which dbus packages should I be looking out for?
+ dbus is running = I do have dbus-daemon running, is it the right instance/in the right mode?
+ The env variable DBUS_SESSION_BUS_ADDRESS is really set = yes, I see it set.


Thanks again!

**Comment by ackerleytng** [comment]
I fixed it! For anyone who might drop by:

+ The dbus-daemon that is running as `--system` is NOT what you're looking for. The one you're looking for should be something like `dbus-daemon ... --session` and should be running as your user, not dbus, not root.
+ if you copy xinitrc from the `/etc` directory, as in #238, it does this weird `eval $(dbus-launch --sh-syntax --with-session)` but doesn't actually specify the session as an argument, hence `dbus-daemon` exits immediately. The eval does set the environment variables, which is doubly bad because if you manually run `dunst`, it will try and connect to the `dbus-daemon` that is not running.

My fix is that in my ,xinitrc, I insert
```
exec dbus-launch i3
```
Note: without the `--exit-with-session` part, so that dbus-daemon keeps running after dbus-launch. And there's no point adding `--sh-syntax` since we're not evaluating the result.
