### ISSUE TITLE
fullscreen and icewm

### ISSUE THREAD

**Issue by zaza42** [dunst-project/dunst#613]
- Version: `1.4.0`
- Install type: `manually created package with -Os and -flto flags`
- Distro and version: `Debian sid+experimental`
- Window manager: `IceWM 1.5.3`

The new fullscreen feature acts weird to me, especially pushback. When I do fullscreen in urxvt (f11), the first time the notification gets disappeared, but when switch back from fullscreen, nothing shown. Dunst is only triggered, when i activate another window; then the notification reappears. 
The second try with another notification message and fullscreened urxvt doesn't hide the notification window at all.

I think this bug can be easily reproduced with icewm + urxvt.

Bonus: the delayed (pushbacked) notification can't be closed with ctrl+space until i activate another window.

The lines I used in dunstrc:
```
[fullscreen_delay_everything]
    fullscreen = pushback
[fullscreen_show_critical]
    msg_urgency = critical
    fullscreen = pushback
```
And I've also tried `fullscreen = pushback` in `[global]` section.

**Comment by tsipinakis** [comment]
That's weird, it works perfectly on i3, iceWM must be doing something different with the fullscreen hints/events.

I'll setup iceWM in a VM later today to try and reproduce this.

**Comment by tsipinakis** [comment]
I apologize for the unreasonably huge delay on this issue, finally got some time to figure this one out.

The problem is the following:
We check whether there is a fullscreen window available every time one of the following events is sent: `FocusIn`, `FocusOut`, `PropertyNotify`.
In my WM (i3) I observe that the following events are sent:
```
(window enters fullscreen)
...
PropertyNotify: _NET_CLIENT_LIST_STACKING
PropertyNotify: _NET_CLIENT_LIST
...

(window exits fullscreen)
...
PropertyNotify: _NET_CLIENT_LIST_STACKING
PropertyNotify: _NET_CLIENT_LIST
...
```
However, with IceWM the above events are only sent when fullscreen is entered but not when it exits. It works correctly when you switch focus to another window as we are also monitoring the `Focus{In,Out}` events for redundancy, so that partly saved us here.

What's still not clear to me is whether this is a bug in IceWM or if it's by design and we are updating on the wrong hints.

**Comment by tsipinakis** [comment]
I've opened an issue on IceWm's repo as well, monitor bbidulock/icewm#347.

**Comment by tsipinakis** [comment]
I've put together a band-aid solution by forcing dunst to update the fullscreen status on `ConfigureNotify` events. It seems to work just fine in this case and hopefully all others.

This is not a proper fix however. I've opened #637 to try and work out a better one at a later date.
