### ISSUE TITLE
The optional 'dunstify' executable isn't installed

### ISSUE THREAD

**Issue by yurivict** [dunst-project/dunst#623]
Please add it to the 'install' target when built.

**Comment by tsipinakis** [comment]
Are you requesting this because the downstream distro you're using doesn't include dunstify or because you're building from source and want to install dunstify globally?

Dunstify doesn't do anything dunst-specific and should work with any notification daemon so I'm of the opinion that it should be packaged separately in distributions if at all. (Separate binary-package in debian terminology). I don't want to add it to the default install target for that reason - it should be treated as a standalone notification client.

We have plans to create a proper command line client to support more advanced usecases see #445 which will be shipped with dunst when it's done as some of its options will only work with dunst and not other daemons.
