### ISSUE TITLE
Trailing comments are no longer accepted

### ISSUE THREAD

**Issue by BlackCapCoder** [dunst-project/dunst#626]
If a line in the config file ends with a comment it is ignored. This is a regression from the last version I had of dunst, whatever that was (I'm on Arch Linux).

```ini
[urgency_normal]
    background = "#0A0A0B" # BG
    foreground = "#86ace1" # FG
```

```bash
> dunst -- version
Dunst - A customizable and lightweight notification-daemon 1.4.0 (2019-03-30)

> dunst &
> notify-send test
WARNING: Invalid color string: '"#86ace1" # FG'
WARNING: Invalid color string: '"#0A0A0B" # BG'
WARNING: Invalid color string: '"#86ace1" # FG'                                                                                                     
WARNING: Invalid color string: '"#0A0A0B" # BG'
```

Visually dunst pops up with both the foreground and background color being black.

The reason this is causing me issues is that I have this tucked away in a script somewhere:
```bash
sed -i "s/^.*# BG/    background = \"$color0\" # BG/g;s/^.*# FG/    foreground = \"$foreground\" # FG/g;" ~/.config/dunst/dunstrc
```

IE: It is useful to have those trailing comments there to be able to locate the lines with tools that only consider a single line at a time.

**Comment by tsipinakis** [comment]
The broken commit is 6cc7ca361aae2b98c3ab6d7ec2b650c425ffbc4e.

@BlackCapCoder Can you try compiling and testing https://github.com/tsipinakis/dunst/commit/d6bd50666947af2d9da7f6db186104d337cb43a5 to verify it also works for you? (and that I didn't break anything else in the process ;) )

Here's what I found by digging around in the source for future explorers:

The warning was already there in 1.3 because before we always removed leading quotes so it was able to parse the hex value before [`string_to_color`](https://github.com/dunst-project/dunst/blob/6cab7891549d6deb110179c0bb0c2cc62bb17b66/src/draw.c#L54-L63) found an invalid character (the end quote and comment).

That commit changed it so we only strip the leading quotes if there is a matching quote at the end of the string but that is not found if there is a trailing comment, leading to trying to parse `"#84ace1" # FG` as a hex value by 1) skipping the first character (assumes it was the `#`) 2) parsing the rest of the string as a hex value, which fails as soon as it meets the `#`.

**Comment by BlackCapCoder** [comment]
@tsipinakis It works for me!
