### ISSUE TITLE
Automatic width broken on 1.4

### ISSUE THREAD

**Issue by PMunch** [dunst-project/dunst#628]
After updating to 1.4.0 I noticed that my old geometry of `-50x0+25+-1` had stopped working. Poking around I found that it was the `-50` that caused the issue as it would no longer be the full width of the monitor minus 50 pixels.

So it seems like something to do with monitor width detection, or the logic surrounding negative numbers in geometry might be broken.

**Comment by tsipinakis** [comment]
Ok, that was a pretty stupid mistake on my part. The bug comes from https://github.com/dunst-project/dunst/commit/a7fd3cb0ec9255ff5bc13cc614b714e946fda122

In `x_parse_geometry` I'm marking that there's a negative width in the `settings.geometry` rather than the `geometry` struct that is being constructed.

I guess that's the price to pay for doing a major refactor in an untested part of the code, sorry for the trouble!
