### ISSUE TITLE
Follow link to Youtube from notification

### ISSUE THREAD

**Issue by schattenkrieger** [dunst-project/dunst#629]
Hello everyone,

not really a bug but dont know where i can find any information of if it possible at all.
I have allowed youtuble to display notifications via google chrome. they are nicely rendered via dunst, but i have not found a way to actually go to the mentioned video via the notification. Via the context menu i can open chrome with the youtube page, but just the normal landig page. is there a way to have chrome open with the actual video "advertised" in the notification?

**Comment by tsipinakis** [comment]
Hi,

The only 2 options I can think of to do that is via the context menu as you mentioned. So either youtube includes the URL somewhere on the notification or youtube again defines an action to open that specific video.

You can use `dunst -print` to see all the information the client is sending us on stdout. Nothing else we can do if we don't have something to reference the video.

The only way to actually achieve what you mentioned, since you obviously can't modify the notification code youtube is using, would be to either write a small script or browser plugin that detects the events you're looking to be notified of and include an action or the URL as I mentioned above.
