### ISSUE TITLE
The timeout value in dunst wraps around

### ISSUE THREAD

**Issue by hbakken** [dunst-project/dunst#646]
dunst internally stores timeouts in microseconds, in a signed 32 bit integer, which wraps around at 2147484, which corresponds to ~40 minutes.  Having timeouts longer than that is not unreasonable, so the wrapping should be fixed.

notify-send -t 2147483 foo
will stay on the screen for 35 minutes, while
notify-send -t 2147484 foo
will use the default (for me, 10s)

### Installation info

- Version: Dunst - A customizable and lightweight notification-daemon 1.3.2
- Install type: package
- Distro and version: Fedora 30

**Comment by tsipinakis** [comment]
I prompted @hbakken to created this issue after a short discussion about the issue on IRC.

What completely flew over my head in that discussion was that it was overflowing on the _32 bit_ boundary not the 64 bit one. After working that out it was dead simple to pinpoint this, and it got me wondering how I missed that in the review :man_facepalming:.

@bebehei Posting the patch here since you self-assigned this, not sure if you're preparing a PR with anything else.

```diff
diff --git a/src/dbus.c b/src/dbus.c
index 741a1c5..b2fc2cb 100644
--- a/src/dbus.c
+++ b/src/dbus.c
@@ -285,8 +285,9 @@ static struct notification *dbus_message_to_notification(const gchar *sender, GV
                 }
         }
 
-        if (timeout >= 0)
-                n->timeout = timeout * 1000;
+        if (timeout >= 0) {
+                n->timeout = ((gint64)timeout) * 1000;
+        }
 
         g_variant_unref(hints);
         g_variant_type_free(required_type);
```

**Comment by bebehei** [comment]
Thanks for the hint. I would have searched pretty long. I'll write a DBus test for this probably.
