### ISSUE TITLE
Couldn't start dunst via systemctl

### ISSUE THREAD

**Issue by foureyedengineer** [dunst-project/dunst#652]
I've installed dunst and to test it I did the following command
`systemctl restart --user dunst.service`

However when I run that it gives me an error:
```
dunst.service - Dunst notification daemon
   Loaded: loaded (/usr/lib/systemd/user/dunst.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2019-08-11 17:26:49 EDT; 3min 2s ago
     Docs: man:dunst(1)
  Process: 18001 ExecStart=/usr/bin/dunst (code=exited, status=1/FAILURE)
 Main PID: 18001 (code=exited, status=1/FAILURE)

Aug 11 17:26:49 LinuxMachine-Mint systemd[17648]: Starting Dunst notification daemon...
Aug 11 17:26:49 LinuxMachine-Mint dunst[18001]: BadAccess (attempt to access private resource denied)
Aug 11 17:26:49 LinuxMachine-Mint dunst[18001]: BadAccess (attempt to access private resource denied)
Aug 11 17:26:49 LinuxMachine-Mint dunst[18001]: Unable to grab key "ctrl+grave"
Aug 11 17:26:49 LinuxMachine-Mint dunst[18001]: Cannot acquire 'org.freedesktop.Notifications': Name is acquired by PID '17762'.
Aug 11 17:26:49 LinuxMachine-Mint systemd[17648]: dunst.service: Main process exited, code=exited, status=1/FAILURE
Aug 11 17:26:49 LinuxMachine-Mint systemd[17648]: dunst.service: Failed with result 'exit-code'.
Aug 11 17:26:49 LinuxMachine-Mint systemd[17648]: Failed to start Dunst notification daemon.

```
I looked at issue 347 but it looks like their errors are different from mine.

I should add that when I do send something manually:
`notify-send "test"`
It works fine but it doesn't seem to pop up any other time (when I download something for example)

Can I have some assistance with this please? Thank you!

**Comment by foureyedengineer** [comment]
I should add then when I do send something manually: 
`notify-send "test"`

It works fine but it doesn't seem to pop up any other time (when I download something for example)

**Comment by bebehei** [comment]
Which dunst version do you have? Which process has got the PID 17762? The NotifyOSD?

Either remove the specific notification manager package or use the FAQ entry ["How to switch back to notify-osd?"](https://dunst-project.org/faq/#how-to-switch-back-to-notify-osd).

But respect the following line:

> If you want to switch back to dunst again, first define `SERVICE=org.knopwob.dunst` and re-execute the `ln` command.

**Comment by tsipinakis** [comment]
```
Aug 11 17:26:49 LinuxMachine-Mint dunst[18001]: BadAccess (attempt to access private resource denied)
Aug 11 17:26:49 LinuxMachine-Mint dunst[18001]: BadAccess (attempt to access private resource denied)
Aug 11 17:26:49 LinuxMachine-Mint dunst[18001]: Unable to grab key "ctrl+grave"
```

From these I would assume it's dunst that's already running outside of systemd

**Comment by foureyedengineer** [comment]
> Which dunst version do you have? Which process has got the PID 17762? The NotifyOSD?
> 
> Either remove the specific notification manager package or use the FAQ entry ["How to switch back to notify-osd?"](https://dunst-project.org/faq/#how-to-switch-back-to-notify-osd).
> 
> But respect the following line:
> 
> > If you want to switch back to dunst again, first define `SERVICE=org.knopwob.dunst` and re-execute the `ln` command.

dunst is v1.4.1-1-g6c4eeda

I don't know how to change a ton of things since I am still kind of learning so I'll take a look at that link you sent me!




> ```
> Aug 11 17:26:49 LinuxMachine-Mint dunst[18001]: BadAccess (attempt to access private resource denied)
> Aug 11 17:26:49 LinuxMachine-Mint dunst[18001]: BadAccess (attempt to access private resource denied)
> Aug 11 17:26:49 LinuxMachine-Mint dunst[18001]: Unable to grab key "ctrl+grave"
> ```
> 
> From these I would assume it's dunst that's already running outside of systemd

How can you tell? Not to be mean, just curious!

**Comment by bebehei** [comment]
> How can you tell? Not to be mean, just curious!

If you start dunst, It's configured to start listening on the DBus Name `org.freedesktop.Notifications` and grab the keyboard shortcut `ctrl+grave`. If you start a second dunst instance, it'll fail to listen on the DBus Name (as the first instance blocks the name) and it'll fail to grab the keyboard shortcut (as the first instance already grabbed the keyboard shortcut and only one process is allowed to grab the same keyboard shortcut).

It's not it has to be dunst. You could have configured your Desktop to grab `ctrl+grave` and also have another Notification manager runnung. We're also not 100% sure that it has to be dunst, but it's a clue with a high probability and additionally easy to verify or falsify. Just run `systemctl restart dunst; systemctl status dunst; pgrep dunst` and send the output.

---

> ```
> Aug 11 17:26:49 LinuxMachine-Mint dunst[18001]: Cannot acquire 'org.freedesktop.Notifications': Name is acquired by PID '17762'.
> ```

@tsipinakis This may be a bit off topic, but I've got another interesting thing:

In commit https://github.com/dunst-project/dunst/commit/5f4d9c6685ccf3872e324ae49cf4e79a18418672#diff-03d575cd4eb2ea9e6c4726831a418503L511

I've added the output to be more specific. Since this commit is contained first in tag 1.4.0, the output has to be `Name acquired by 'XY' with PID '17762'` if it would be really version `v1.4.1-1-g6c4eeda` of dunst.
