### ISSUE TITLE
Close notification when default action has been executed

### ISSUE THREAD

**Issue by remolueoend** [dunst-project/dunst#660]
Hey everyone, first of all thanks for the great work on dunst!

After playing around with the config I realized that notifications do not get closed after one of their actions get executed (either via dmenu or mouse button). Is this intentional? My C skills are - nicely said - nonexistent, but I've looked through `menu.c::invoke_action` and `dbus.c::signal_action_invoked` and was not able to find any logic related to close a notification, so I assume it is not configurable.

My question here is: Does it really make sense to keep a notification on screen after the user has executed one of its actions? For me this implies that the user has taken notice of the notification and thus it can be removed. But then again I am probably not aware of all other possible use cases. 

### Installation info

- Version: `1.4.1`
- Install type: `package`
- Distro and version: `5.2.9-arch1-1-ARCH`

**Comment by tsipinakis** [comment]
Closing a notification has the side-effect of notifying the sender that it was dismissed, which in most cases causes it to stop listening for further actions. This is why we don't allow actions to be called from notifications in history.
So implementing this would mean you can't perform two actions on the same notification.

And in any case, closing a notification is always a single keystroke away.

**Comment by bebehei** [comment]
@tsipinakis I guess there is a specific problem. And the problem is, that an "activated" notification didn't get closed.

I've learned, that notifications aren't invalidated by the standard and dunst hasn't got such a thing. I've had a hard time searching for it in the code. But no, dunst doesn't close any notification, which it sent an `ActionInvoked` signal for. So, technically @remolueoend is right.

But on the other side, the standard doesn't mandate it. It only mandates, that you have to invalidate the notification id after the `NotificationClosed` signal. So technically, it would be correct, sending hundreds of actions without closing the notification.

And here is the point: All clients call `CloseNotification` with the ID of the notification after receiving the `ActionInvoked` for it. So the client closes the notification after invoking the action. It's not dunst.

I guess, there is a "misbehaving" client.

@remolueoend Before triggering a notification call
```
dbus-monitor type=signal,member=ActionInvoked,path=/org/freedesktop/Notifications type=signal,member=NotificationClosed,path=/org/freedesktop/Notifications type=method_call,member=CloseNotification,path=/org/freedesktop/Notifications
```
in the terminal and watch the output while triggering the action. It should give the following output:

```
signal time=1567704022.384890 sender=:1.752 -> destination=:1.769 serial=63 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=ActionInvoked
   uint32 16
   string "a"
method call time=1567704022.385782 sender=:1.769 -> destination=:1.752 serial=8 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=CloseNotification
   uint32 16
signal time=1567704022.387560 sender=:1.752 -> destination=:1.769 serial=64 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=NotificationClosed
   uint32 16
   uint32 3
```

**Comment by remolueoend** [comment]
Thank you both very much for the detailed explanations, looks like I haven't really understood who is responsible for the notification and how the communication works between sender and dunst. Great to know!

@bebehei I checked and it indeed looks like the clients are "misbehaving", checked for both Slack and whatsapp-nativefier (both Arch AUR packages). They do not close their own notification (but dunst does after the configured timeout):

```
signal time=1567765740.311768 sender=:1.1 -> destination=:1.82 serial=21 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=ActionInvoked
   uint32 5
   string "default"
signal time=1567765746.674149 sender=:1.1 -> destination=:1.82 serial=22 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=NotificationClose`
```

Thanks again for your help, I close this issue. If I ever want to get my fingers on some C codebase, I might play around on a fork, to tell dunst by config to close a notification after its single "default" action was invoked. Sounds like some fun. :+1:
