### ISSUE TITLE
Markup doesn't work when message contains "&" (ampersand) symbol and some others

### ISSUE THREAD

**Issue by didiksupriadi41** [dunst-project/dunst#662]
Dunst markup is not working when the messages contain "&" symbol.
there might be other symbols that potentially cause the same error.
Can be reproduced with `notify-send` command and `dunst` installed.

Reproducible: Always

Steps to Reproduce:
1. For simple setup, write `format=%s: %b` in dunst configuration file
2. Restart dunst, `killall dunst; dunst`
(or just `killall dunst` if it's the only notif daemon installed)
3. Let's try \<b\> tags.
4. Test with `notify-send "<b>hel&lo</b>" "world"` and `notify-send "<b>hello</b>" "wor&ld"` to see buggy results.

Actual Results:  
"hel&lo: world" and "hello: wor&ld", respectively, with no bold effect.

Expected Results:  
"hel&lo: world" and "hello: wor&ld", respectively, Bold on both first word.

I notice there might be other symbols that have same behavior as this one.

- Version: `Dunst - A customizable and lightweight notification-daemon 1.3.2`
- Install type: `package`
- Distro and version: `Fedora 30 `

**Comment by tsipinakis** [comment]
See #546, #616 

This issue was basically fixed in #546. Later we disabled markup support in the summary (first part of the message) entirely as it turns out it's not really supported by the notification spec and having it enabled broke some clients with issues similar to this.

Upgrading to 1.4.0 should fix the issue (but sadly will also mean no markup support in the summary)

**Comment by didiksupriadi41** [comment]
Ah, I see.
I hope it has workaround to replace html markup some day.
