### ISSUE TITLE
Feature Request: show notification only in background at urgency_minimal.

### ISSUE THREAD

**Issue by oltodosel** [dunst-project/dunst#663]
At urgency_minimal notifications would be visible only on desktop if there's no window over it.

**Comment by tsipinakis** [comment]
I'm not sure that this would be worth implementing considering the effort it would take.

We'd need to somehow detect if there's a window on the desktop (we already had enough issues with checking for fullscreen windows). And there are are edge cases like figuring out what happens on non tiling window managers.

There's a similar feature implemented that can hide some notifications based on if you're focused on a fullscreen window, perhaps that could cover a lot of the cases something like this would be needed?


---

Otherwise I'd love to hear the usecase for this - what sort of notifications are you trying to hide?

**Comment by oltodosel** [comment]
Wanted it for watching progress of some cron jobs.
Will implement it via conky.
