### ISSUE TITLE
dunstctl: Rename set-running to set-paused

### ISSUE THREAD

**Issue by tsipinakis** [dunst-project/dunst#710]
After looking at #709  the name `set-running` sounds a bit odd to me. It was named like this as this is our internal status name. But for the user facing side `set-paused` is probably more clear.

Bit unfortunate that I noticed this after merging, but thankfully it hasn't been officially released yet so no harm in directly changing it in master.

**Comment by tsipinakis** [comment]
Additionally, `running` can be `is-paused`, to make it clear it's a getter. I looked at all the commands again and hopefully this is the last of the breaking changes on this front.

**Comment by mrossinek** [comment]
I will go ahead and invert the true/false results of both commands to match the `paused` syntax compared to the internal `running` syntax.
Otherwise `is-paused` would return `true` when the internal variable refers to whether its running.

Not sure if this text makes sense but I hope you know what I mean. The code should make it clear.
