### ISSUE TITLE
What do letters in the top left mean?

### ISSUE THREAD

**Issue by Noah-Franks** [dunst-project/dunst#724]
I've seen things like (A) and (U) in the top left for some notifications. What are they supposed to mean?

**Comment by tsipinakis** [comment]
From the [man page](https://github.com/dunst-project/dunst/blob/master/docs/dunst.pod#actions).
> If "show_indicators" is true and a notification has an action, an "(A)" will be prepended to the notification format. Likewise, an "(U)" is prepended to notifications with URLs. It is possible to interact with notifications that have actions regardless of this setting, though it may not be obvious which notifications HAVE actions.

Because we've had this same question a lot (#599, #579), did you take a look at the man page before asking this and didn't find the answer? I don't mind if you didn't, just trying to find ways to improve the documentation and avoid such issues in the future.

**Comment by Noah-Franks** [comment]
Thanks for the answer. 
I checked the website and searched GitHub (somehow 'letter' didn't match #579).
I see too now that it's also in my dunstrc. 

I would have never guessed something like that would be in dunst's man page. I checked notify-send's man page and thought maybe it was a category, and tried a few of them but couldn't get the letters to show up.

**Comment by tsipinakis** [comment]
I'll close this then as it appears to be resolved. I'll also add a link to the documentation on the website so it's more easily discoverable.
