### ISSUE TITLE
Possibility to specify a different config file?

### ISSUE THREAD

**Issue by sdushantha** [dunst-project/dunst#726]
Is it possible to specify a different config file when running `dunstify`? For example in `vim`, you can specify a config file which is not the deafult one by using the `-u <file>` flag. 
I personally think this would be useful because sometimes, I want certain notifications to have a certain geometry. 

### Installation info
- Version: `1.4.1`
- Install type: manually
- Distro and version: `Manjaro 20.0.3 `

**Comment by tsipinakis** [comment]
I think you have a few concepts confused here. `dunstify` doesn't display anything and hence has no config file, it merely sends the notification to `dunst`.

`dunst` is the program/daemon that handles displaying, and due to dbus limitations only one program can be listening for notifications at a time - so you sadly can't run multiple instances unless you get into the ugly hack territory of running multiple dbus daemons.

**Comment by sdushantha** [comment]
Ah okay, that makes sense. Thank you for the quick answer! :)
