### ISSUE TITLE
notifications displayed over xscreensaver

### ISSUE THREAD

**Issue by aidalgol** [dunst-project/dunst#77]
Notifications displayed while `xscreensaver` is running (i.e. the actual screensaver, not just the daemon) are not occluded by the screensaver but displayed in front of it.

This appears to be a known issue: https://bbs.archlinux.org/viewtopic.php?pid=1199831#p1199831

Unless I am misunderstand the problem, the `XScreenSaver(3)` manpage documents an API for querying the state of the screensaver, which may provide a solution to the problem mentioned in the above post.

**Comment by qsuscs** [comment]
I found this issue while searching for a solution, so for future reference, have mine:
```shell
#!/bin/sh
xscreensaver-command -watch | while read event rest; do
        case $event in
                "LOCK"|"BLANK")
                        pkill -USR1 -x -u `id -u` dunst
                        logger Paused dunst
                        ;;
                "UNBLANK")
                        pkill -USR2 -x -u `id -u` dunst
                        logger Resumed dunst
                        ;;
        esac
done
```

This will watch events from XScreensaver and pause and resume dunst, and log so to syslog.  Add and/or remove features (and quotes, because shell) as you please, don’t blame if it sets your house on fire. I don’t know (yet) what happens if XScreensaver exits, so you’ll maybe also need an enterprise loop or so—again, no guarantees.

**Comment by tsipinakis** [comment]
Thanks for the update, always appreciated!

There has been an attempt at fixing this directly - or, at least, improve the situation (see #160) and will be included in the next release.
