### ISSUE TITLE
Progress bar in notification

### ISSUE THREAD

**Issue by fwSmit** [dunst-project/dunst#772]
I recently started using Dunst, and I like the customizabilty it offers. I'm missing one feature however: a progress bar. This is related to #318 from a while ago. Not much has been done about this, so I decided I want to implement something similar. 

The way I would do it is a bit different from the issue above. I would use the progress value %p and use it to draw a bar below the text of the notification. The text representation of %p would still be the default, so you would have to activate it via the config (or a command line argument?).

![Image of what it would look like](https://i.ibb.co/hXhccdb/notification-edited.png)
_This is what it would look like_

Is this be a feature that would be considered to be merged into dunst?

**Comment by tsipinakis** [comment]
Since no-one has picked this in so long, any form of it is welcome. In some ways I like your design better than the 'progress bar background' proposed in #318.

> The text representation of %p would still be the default, so you would have to activate it via the config (or a command line argument?).

I'd be fine with making this the default as well, it's a clear improvement from the current situation where, in the default format, progress isn't even visible.

**Comment by tsipinakis** [comment]
Implemented in #775.
