### ISSUE TITLE
clean up dunst dbus service name conflict errors in journalctl log on boot

### ISSUE THREAD

**Issue by garberw** [dunst-project/dunst#820]
What I found out about starting up dunst if there is any confusion:  if you have a service file e.g. <pre><code>/usr/share/dbus-1/services/org.knopwob.dunst.service</code></pre> then you should not add dunst to the startup-applications for the desktop because dbus will trigger dunst automatically.  You also should not enable the service in --user mode e.g. 
<pre><code>systemctl enable --user dunst</code></pre>

There were MINOR errors visible in the boot log <pre><code>$ journalctl -b -p3
Feb 08 17:11:25 electron.localdomain dbus-broker-launch[1751]: Ignoring duplicate name 'org.freedesktop.Notifications' in service file '/usr/share//dbus-1/services/org.knopwob.dunst.service'
Feb 08 17:11:25 electron.localdomain dbus-broker-launch[1751]: Ignoring duplicate name 'org.freedesktop.Notifications' in service file '/usr/share//dbus-1/services/org.kde.plasma.Notifications.service'
Feb 08 17:11:25 electron.localdomain dbus-broker-launch[1751]: Ignoring duplicate name 'org.freedesktop.FileManager1' in service file '/usr/share//dbus-1/services/org.mate.freedesktop.FileManager1.service'
Feb 08 17:11:26 electron.localdomain cupsd[1521]: [CGI] ippfind (PID 1660) stopped with status 1!
Feb 08 17:11:26 electron.localdomain cupsd[1521]: [cups-deviced] PID 1649 (driverless) stopped with status 1!
Feb 08 17:11:28 electron.localdomain pulseaudio[1923]: module-rescue-stream is obsolete and should no longer be loaded. Please remove it from your configuration.
Feb 08 17:11:39 electron.localdomain gdm-password][2301]: gkr-pam: unable to locate daemon control file
Feb 08 17:11:42 electron.localdomain dbus-broker-launch[2416]: Ignoring duplicate name 'org.freedesktop.Notifications' in service file '/usr/share//dbus-1/services/org.knopwob.dunst.service'
Feb 08 17:11:42 electron.localdomain dbus-broker-launch[2416]: Ignoring duplicate name 'org.freedesktop.Notifications' in service file '/usr/share//dbus-1/services/org.kde.plasma.Notifications.service'
Feb 08 17:11:42 electron.localdomain dbus-broker-launch[2416]: Ignoring duplicate name 'org.freedesktop.FileManager1' in service file '/usr/share//dbus-1/services/org.mate.freedesktop.FileManager1.service'
Feb 08 17:12:09 electron.localdomain pulseaudio[2672]: GetManagedObjects() failed: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
</code></pre>This is due to the fact that dunst is started by a service file in <pre><code>/usr/share/dbus-1/services</code></pre> and several service files may share the name <pre><code>org.freedesktop.Notifications</code></pre>  To see them, do <pre><code>$ cd /usr/share/dbus-1/services
$ grep -i org.freedesktop.Notifications *.service</code></pre> To fix this, I renamed <pre><code>/usr/share/dbus-1/services/org.knopwob.dunst.service</code></pre>to <pre><code>/usr/share/dbus-1/services/org.knopwob.dunst.service.disabled</code></pre>and I made  <pre><code>/usr/share/dbus-1/services/org.freedesktop.Notifications.service</code></pre>a symbolic link to that file.  Next do <pre><code>$ grep -i org.freedesktop.Notifications *.service</code></pre>and if any other services match, rename them by adding ".disabled" to the end of the filename.  Then you will have ZERO minor boot errors due to this issue.

### Installation info

- Version: `v1.5.0-87-g814e620`
- Install type: `manual from git`
- Distro and version: ` fedora 32`

**Comment by fwSmit** [comment]
As I've said [here](https://github.com/dunst-project/dunst/issues/817#issuecomment-775799936), you can link org.freedesktop.Notifications.service to org.knopwob.dunst.service, instead of moving any of the service files. As far as I know that prevents other notification daemon from being started. Could you try to see if that prevents the warnings as well?

**Comment by garberw** [comment]
no it does not prevent the warnings; anything listed by the grep command above gives the warnings which come from other desktop environments being installed simultaneously (kde, gnome, mate); each has a notification daemon.  Warnings are NOT VERY IMPORTANT since they do not have any bad effect but they do appear in "journalctl -p3" which is a high-level warning so I complained.  Sorry if frivolous.  It may be seen as a packaging problem for the fedora packager????

**Comment by fwSmit** [comment]
No it's okay, it's good that you're pointing out this issue. The deeper issue here is that there's still no good way for dbus to autostart something that's provided by multiple dbus services. As far as I can tell, it's not even guaranteed that my solution above should work, as the ordering of services in the same directory is not defined. What may work though is to add a service to /usr/local/share/dbus-1, which will have precedence over /usr/share/dbus-1. I don't know if this will get rid of the error messages though.
Here's a good writeup which highlights some of the issues with the current way it's handled: https://kevinlocke.name/bits/2020/04/12/resolving-desktop-notifications-dbus-service-conflicts/.

Because of these issues I'll go ahead and recommend everyone not to rely on dbus autostarting. I would currently recommend to use your desktop environment / window manager's way of starting services at boot time. When we've fixed the systemd service that would work as well.

**Comment by garberw** [comment]
yes !!!! I updated by <pre><code>cd /usr/lib/systemd/user/
mv dunst.service dunst.service.disabled
systemctl daemon-reload</code></pre>and created a desktop envoironment (gnome or mate or kde etc.) autostart-on-login file.  This works and you can use the desktop environment "startup preferences" in mate to turn it on or off which is convenient.  This also solves<A>https://github.com/dunst-project/dunst/issues/821</A>.

**Comment by bebehei** [comment]
We had similar issues previously. Therefore, i've created a [FAQ for it](https://dunst-project.org/faq/#how-to-switch-back-to-notify-osd).

IIRC, whenever multiple DBus service files provide the same service, the file listed by a `find` first, is the file which wins. This is an absolute shitshow.

Therefore we recommend there in the article, to link the wanted DBus service into higher prioritized directories.


---

Also It's preferred to use `systemctl taint` instead of manually `mv`-ing files in `/usr`.

**Comment by bebehei** [comment]
After all, I don't see any action, the dunst project could change here to improve the situation. This is solely a packaging problem/DBus architecture problem.

**Comment by fwSmit** [comment]
> After all, I don't see any action, the dunst project could change here to improve the situation. This is solely a packaging problem/DBus architecture problem.

Yes, apart from documentation we can't do much here.
