### ISSUE TITLE
Question: check if notifications are visible

### ISSUE THREAD

**Issue by and3rson** [dunst-project/dunst#978]
I'm using Sway and am trying to map my `Escape` key to:

- If any notification is visible: close all notifications via `dunstctl`
- If none are visible: re-send `Escape` key via `wtype`

This way I can use my `Escape` key to be able to close the notifications and still use it as-is.

Is it possible to somehow check if any notifications are currently being displayed by dunst?

**Comment by and3rson** [comment]
I'm blind. Just found the `dusntctl count displayed`. Sorry for making noise!

**Comment by wgmayer0** [comment]
How would I apply this in xmonad?

**Comment by fwsmit** [comment]
You would need to use something like `xdotool key Escape` instead of `wtype -P Escape`

**Comment by wgmayer0** [comment]
I can do that but now every escape sent will be a simulated escape. I could see that causing problems down the line as simulated escapes don't work as well as a real escape keycode being sent to the machine. Could/would Dunst upstream add the escape feature again to Dunst? I don't understand why it was removed.

**Comment by geekosaur** [comment]
X11 marks all synthetic events as `send_event`s, and many X11 clients ignore any event with the `send_event` flag set for security reasons.

**Comment by wgmayer0** [comment]
> In what way does the stimulated escape work differently?

I have seen many, many people complaining about the keybinding change. I think it is a poor design decision to leave things to `xdotool` because the key is simulated and interpreted as simulated by X11. `xdotool` is usable for some things but generally regarded unstable and ineffective.

List of examples:
-Vim was ignoring `xdotool key escape` when I was pressing it

*This list will continue to grow*

I think the best option is to implement the keybindings again. I can't emphasize how much users need this feature.

**Comment by geekosaur** [comment]
Sadly I think dunst is yet another program which is effectively dropping X11 support in favor of a window system that is still demonstrably not ready for production use. I suggest forking it at the last commit that was usable.

**Comment by geekosaur** [comment]
Sadly I think dunst is yet another program which is effectively dropping X11 support in favor of a window system that is still demonstrably not ready for production use. I suggest forking it at the last commit that was usable.

**Comment by geekosaur** [comment]
Sadly I think dunst is yet another program which is effectively dropping X11 support in favor of a window system that is still demonstrably not ready for production use. I suggest forking it at the last commit that was usable.

**Comment by geekosaur** [comment]
(sorry, I had a network problem that resulted in something like 4 copies of that last message. I've deleted the extraneous ones.)

**Comment by fwsmit** [comment]
We are not dropping X11 support at all! It's just that when this feature was dropped it was not clear to me that people relied on being able to enable the shortcut only when notifications are up. The alternative of setting your shortcuts via your window manager seemed exactly the same with less code. Note that shortcuts via the dunst settings were never a thing in the wayland version of dunst and probably never will. To make the dunst's configuration more consistent, we dropped 
Since it seems like there isn't a good alternative on X11, **dunst will re-enable shortcuts in the next version**. I'm sorry for the inconvenience this caused.
Since I'm quite busy at the moment this might take a bit, so if you want to see this more quickly, you can open a pull request which adds the feature back.

**Comment by wgmayer0** [comment]
Thank you!

**Comment by fwsmit** [comment]
Is anyone able to test them when the shortcuts are implemented again?

**Comment by wgmayer0** [comment]
Hi Friso,

Do you know when this will be released on Arch Linux?

Thanks,

**Comment by fwsmit** [comment]
I'm working to make a release today. Arch is pretty fast to release their build most of the time.

**Comment by fwsmit** [comment]
Dunst 1.8.0 has been released (with shortcuts again).
