### ISSUE TITLE
Using notify-send not respect any markup.

### ISSUE THREAD

**Issue by hspak** [dunst-project/dunst#99]
Spawning dunst through notify-send does not respect the bold, underline and italics.

**Comment by Phyks** [comment]
Same problem here, due to the use of `notify-send` I get a bunch of errors in the logs and miss some notifications.

Is there a standard way to preprocess the string before passing it to notify-send? (Am having the issue with custom scripts and a Thunderbird extension to use system notifications rather than built-in ones (and "@" in email addresses is an issue)).

Thanks

**Comment by tsipinakis** [comment]
Fixed with #279, added option to control how markup is handled `full` to parse markup, `strip` to strip it and `no` to handle everything as plain text.

@Phyks If markup is enabled, the standard way to escape notifications is to replace all instances of `<`, `>`, `&` with `&lt;`, `&gt` and `&amp;` respectively.

**Comment by Phyks** [comment]
@tsipinakis Thanks!
